version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: schema_sample
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
