name: Generate DB Schema Document
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  tbls:
    if: github.event.pull_request.draft == false
    name: "tbls"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create database
        run: |
          make setup_db
      - name: install tbls then generate DB schema document
        run: source <(curl https://raw.githubusercontent.com/k1LoW/tbls/main/use) && make schema
      - uses: dev-hato/actions-diff-pr-management@v1.1.1
        with:
          github-token: ${{ secrets.CI_TOKEN }}
          branch-name-prefix: fix-tbls
          pr-title-prefix: DB schema document修正
          pr-description-prefix: DB schema documentを修正しました。
